const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ids=[...html.split('<script>')[0].matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(ids).size,ids.length,'duplicate static IDs');
const functions=[...code.matchAll(/^function (\w+)\(/gm)].map(x=>x[1]);assert.equal(new Set(functions).size,functions.length,'duplicate functions');
for(const m of code.matchAll(/getElementById\('([^']+)'\)/g))assert.ok(ids.includes(m[1]),'missing ID '+m[1]);
const elements=new Map(),storage={},alerts=[];let failStorage=false;
function el(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',focus(){},click(){},style:{},querySelector:()=>el(id+'span'),classList:{add(){},remove(){},toggle(){},contains(){return true}},parentElement:{clientWidth:390},getContext(){return new Proxy({},{get:()=>()=>{}})}});return elements.get(id)}
class Reader{readAsText(file){this.result=file.text;this.onload();}}
const ctx=vm.createContext({console,Date,Math,Set,Number,String,Object,Array,JSON,Blob,encodeURIComponent,decodeURIComponent,setTimeout(){},FileReader:Reader,localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>{if(failStorage)throw Error('quota');storage[k]=v}},document:{getElementById:el,querySelectorAll:()=>[]},window:{devicePixelRatio:1,addEventListener(){}},navigator:{},location:{protocol:'http:'},confirm:()=>true,alert:m=>alerts.push(m)});
new vm.Script(code);vm.runInContext(code,ctx);const run=s=>vm.runInContext(s,ctx);const json=s=>JSON.parse(run('JSON.stringify('+s+')'));
let passed=0;function test(name,body){run("S=freshState();S.date='2026-10-07';unreadableStorage=false;");body();passed++;console.log('PASS '+name);}
test('food deletion retains historical totals and rows',()=>{run("S.foods=[{id:'f',name:'Egg',emoji:'x',cal:400,prot:30}];S.logs[S.date]=[{id:'l',fid:'f',qty:1,time:'12:00'}];S.dayTypes[S.date]='train';delFood('f')");assert.deepEqual(json('getTotals()'),{cal:400,prot:30});assert.equal(run('calcTotalDeficit()'),2300);assert.match(el('logList').innerHTML,/Egg/);});
test('food edits update references and snapshots',()=>{run("S.foods=[{id:'f',name:'Egg',emoji:'x',cal:400,prot:30}];S.logs[S.date]=[{id:'l',fid:'f',qty:1,time:'12:00'}];editingFoodId='f'");el('editFoodName').value='New';el('editFoodCal').value='500';el('editFoodProt').value='40';run('saveEditedFood()');assert.equal(run('getTotals().cal'),500);assert.equal(run('S.logs[S.date][0].foodSnapshot.cal'),500);});
test('workout same day completion, next cycle, undo preserve full history',()=>{run("S.workoutHistory={'2026-10-06':['legs','chest','biceps','triceps','shoulders']};toggleWorkoutPart('back')");assert.deepEqual(json('getWorkoutCycleState().selectedParts'),[]);assert.equal(el('workoutClearTodayBtn').disabled,false);run("toggleWorkoutPart('legs')");assert.deepEqual(json('getWorkoutDaily()'),['back','legs']);assert.deepEqual(json('getWorkoutCycleState().todaySelections'),['legs']);run('undoWorkoutAction()');assert.deepEqual(json('getWorkoutDaily()'),['back']);run('undoWorkoutAction()');assert.deepEqual(json('getWorkoutDaily()'),[]);assert.deepEqual(json('getWorkoutCycleState().lockedParts'),['legs','chest','biceps','triceps','shoulders']);});
test('multiple cycles and toggling change only active target',()=>{run("WORKOUT_PARTS.forEach(toggleWorkoutPart);toggleWorkoutPart('back');toggleWorkoutPart('shoulders');toggleWorkoutPart('back')");assert.deepEqual(json('getWorkoutDaily()'),['legs','chest','biceps','triceps','shoulders','back','shoulders']);assert.deepEqual(json('getWorkoutCycleState().todaySelections'),['shoulders']);});
test('clear workout affects only selected day and undo restores completion',()=>{run("S.workoutHistory={'2026-10-06':['legs','chest','biceps','triceps','shoulders']};toggleWorkoutPart('back');clearWorkoutToday()");assert.equal(run("S.workoutHistory['2026-10-06'].length"),5);assert.deepEqual(json('getWorkoutCycleState().lockedParts'),['legs','chest','biceps','triceps','shoulders']);run('undoWorkoutAction()');assert.equal(run('getWorkoutCycleState().completedOnTarget'),true);});
test('full clear erases undo and retains targets',()=>{run("S.workoutUndo={[S.date]:[['legs']]};S.goals.cal=2000;confirmClear();undoWorkoutAction()");assert.deepEqual(json('S.workoutHistory'),{});assert.deepEqual(json('S.workoutUndo'),{});assert.equal(run('S.goals.cal'),2000);});
test('empty weight input retains all history, repeated values recorded',()=>{el('weightInput').value='74.1';run('saveWeight();saveWeight()');assert.equal(run('getWeightEntries().length'),2);el('weightInput').value='';run('saveWeight()');assert.equal(run('getWeightEntries().length'),2);run("deleteWeightEntry('2026-10-07',0)");assert.equal(run('getWeightEntries().length'),1);});
test('weight chronology prioritizes record date and time',()=>{run("S.weightHistory={'2026-10-01':[{weight:74,time:'10:00',stamp:200}],'2026-10-07':[{weight:75,time:'09:00',stamp:100}]}");assert.deepEqual(json('getWeightEntries().map(e=>e.date)'),['2026-10-01','2026-10-07']);});
test('legacy weights migration remains compatible',()=>{run("S.weights={'2026-10-01':75};normalizeWeightHistory();save()");assert.equal(run("S.weightHistory['2026-10-01'][0].weight"),75);assert.equal(JSON.parse(storage.nlog3).weights['2026-10-01'],75);});
test('date switching refreshes workout labels',()=>{run('renderWorkoutPage();changeDate(1)');assert.match(el('workoutDateLabel').textContent,/10月8日/);run('goToday()');assert.equal(el('workoutDateLabel').textContent,run('fmtDate(todayStr())'));});
test('mode toggle and no-meal deficit exclusion',()=>{run("setDayType('train')");assert.equal(run('calcTotalDeficit()'),0);assert.match(el('todayDefLbl').textContent,/食事を記録/);run("setDayType('train')");assert.equal(run('getBurn(S.date)'),null);});
test('burn labels follow configured consumption',()=>{run('S.deficit.burnTrain=2800;S.deficit.burnOff=2300;renderDayMode()');assert.equal(el('btnTrainspan').textContent,'消費 2800 kcal');assert.equal(el('btnOffspan').textContent,'消費 2300 kcal');});
test('frequency counts entries, not quantity',()=>{run("S.logs[S.date]=[{fid:'f',qty:10},{fid:'g',qty:1},{fid:'g',qty:1}]");assert.equal(run("getFoodUseCount('f')"),1);assert.equal(run("getFoodUseCount('g')"),2);});
test('explicit food category overrides name detection',()=>{assert.equal(run("isAlcoholFood({name:'酒粕',category:'food'})"),false);assert.equal(run("isAlcoholFood({name:'ビール'})"),true);});
test('food defaults idempotent and preserve explicit category',()=>{run("S.foods=[{id:'f',name:'酒粕',emoji:'x',cal:100,prot:1,category:'food'}];ensureAlcoholDefaults();ensureAlcoholDefaults()");assert.equal(run('S.foods.length'),9);assert.equal(run('S.foods[0].category'),'food');});
test('HTML in names rendered only as text',()=>{run("S.foods=[{id:'f',name:'<img src=x onerror=alert(1)>',emoji:'<b>x</b>',cal:100,prot:1}];renderFoods()");assert.doesNotMatch(el('foodList').innerHTML,/<img|<b>x/);assert.match(el('foodList').innerHTML,/&lt;img/);});
test('invalid numbers rejected before food/weight mutation',()=>{el('fName').value='bad';el('fCal').value='-1';el('fProt').value='3';run('saveFood()');assert.equal(run('S.foods.length'),0);el('weightInput').value='999999';run('saveWeight()');assert.deepEqual(json('S.weightHistory'),{});});
test('valid backup roundtrip and partial legacy format',()=>{run("S.weights={'2026-10-01':75};S.foods=[{id:'f',name:'x',emoji:'x',cal:100,prot:1}]");assert.equal(run('validateState(parseBackup(JSON.stringify(S))).foods.length'),1);assert.equal(run("validateState({weights:{'2026-10-01':75},goals:{cal:2000}}).goals.prot"),130);});
test('bad JSON/schema leaves memory and stored backup untouched',()=>{run('save()');const before=storage.nlog3;el('importJson').value='x';run("importData({target:{files:[{text:'{\"logs\":null}'}],value:'x'}})");assert.equal(storage.nlog3,before);assert.deepEqual(json('S.logs'),{});assert.match(alerts.at(-1),/失敗/);assert.throws(()=>run("parseBackup('{\"__proto__\":{}}')"));});
test('valid import refreshes all pages and adds defaults',()=>{const backup=run('JSON.stringify(S)');ctx.testBackup=backup;run("importData({target:{files:[{text:testBackup}],value:'x'}})");assert.equal(run('S.foods.length'),8);assert.equal(run('unreadableStorage'),false);});
test('storage failure during import rolls back memory',()=>{run('S.goals.cal=2000;save()');const before=storage.nlog3;failStorage=true;run("importData({target:{files:[{text:JSON.stringify(freshState())}],value:'x'}})");failStorage=false;assert.equal(run('S.goals.cal'),2000);assert.equal(storage.nlog3,before);});
test('old orphan logs are visible and excluded from deficit',()=>{run("S.logs[S.date]=[{id:'lost',fid:'missing',qty:1,time:'12:00'}];S.dayTypes[S.date]='train';renderLog()");assert.equal(run('calcTotalDeficit()'),0);assert.match(el('logList').innerHTML,/栄養値不明/);assert.match(el('todayDefLbl').textContent,/未集計/);assert.match(el('goalCalLbl').textContent,/栄養値不明/);});
test('unreadable stored data is never automatically overwritten',()=>{storage.nlog3='{bad';run('load();addDefaults();ensureAlcoholDefaults();save()');assert.equal(storage.nlog3,'{bad');assert.equal(run('unreadableStorage'),true);});
console.log(`${passed} regression checks passed; syntax, IDs and functions passed.`);
